Feature/roll command
jonasbohmann/democraciv-discord-bot pull request #13
Opened 2020-08-08 02:43 UTC by ArchWizard56

This will add a command to roll dice to the misc module.

2020-08-09 19:16 UTC, jonasbohmann requested changes
Hey, thanks a lot for the PR!

I just added some small nit-picky suggestions, like

- `if isinstance(thing, type_to_check_against):` instead of `if type(thing) is type_to_check_against:`
- PEP8 variable names, `scoreString` -> `score_string`, `specialMessage` -> `special_message` etc.
- f-strings everywhere instead of str.format() and string concatenation with `+`, like `string = f"{string}\n{thing}"` instead of `string = string + "\n" + "{0}".format(thing)`

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +    async def roll(self, ctx, *args):
```suggestion
    async def roll(self, ctx, *, dices):
```

Putting all the arguments in one string, aka "consume rest behaviour", is done like this:

`async def roll(self, ctx, *, args):`

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +    async def roll(self, ctx, *args):
Maybe make the argument name more human sounding? Like `dices`, `dice` or something along the lines of that.

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +            if type(score.detail) is int:
```suggestion
            if isinstance(score.detail, int):
```


It's better do check for types like this:

`if isinstance(score.detail, int):`,

instead of using `type()`.

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +            scoreString = "[{0}]".format(scoreString)
```suggestion
            score_string = f"[{score_string}]"
```

Better to use f-strings here.

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +        msg = "{0}:\n> `{1}` = {2} = {3}".format(ctx.message.author.mention,arg,rolls,roll)
```suggestion
        msg = f"{ctx.author.mention}:\n> `{arg}` = {rolls} = {roll}"
```

Better to use f-strings here.

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +        arg = " ".join(args[:])
See comment at function definition

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +        except (SyntaxError, TypeError, ValueError):
```suggestion
        except (TypeError, ValueError):
```

I'm not sure whether `SyntaxError` can be thrown in that `try` block.

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +                scoreString = scoreString + score.detail
```suggestion
                score_string = f"{score_string}{score.detail}"
```

f-strings would just be a tiny bit faster than string concatenation.

2020-08-09 19:16 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +            msg = msg + "\n" + specialMessage
```suggestion
        if special_message:
            msg = f"{msg}\n{special_message}"
```

2020-08-09 20:04 UTC, ArchWizard56 commented on dciv_bot/module/misc.py
> +        except (SyntaxError, TypeError, ValueError):
If the user input can't be parsed by the library, it throws a syntax error. I didn't see a workaround aside from the try-except block

2020-08-09 20:35 UTC, jonasbohmann commented on dciv_bot/module/misc.py
> +        except (SyntaxError, TypeError, ValueError):
Ah okay, sorry.

2020-08-10 15:13 UTC, merged

2020-08-10 15:13 UTC, jonasbohmann commented
Thanks!